server:
  port: 8080

logging:
  config: classpath:logback.xml
management:
  endpoint:
    logfile:
      external-file: ./logs/json-api.log
  endpoints:
    web:
      exposure:
        include: health,logfile
